### ISSUE TITLE
HOT SNAKES

### ISSUE THREAD

**Issue by jessekrubin** [tdarci/deleteme#1]
I cloned this repo and then deleted ("rm -rf"-ed) it but nothing happened.

Please fix asap.

**Comment by tdarci** [comment]
Dear @jessekrubin, thank you for bringing this to my attention.
I also appreciate the `HOT SNAKES` headline. It really caught my 👁️ .

In your repro case you say:
1. I cloned this repo
2. deleted ("rm -rf"-ed) it
3. nothing happened

You do not indicate what the expected outcome was.
In this case, fortunately, you will find this is a feature, not a bug, as "nothing happened" is the intended behavior.
Once you have rmrfed the repo, you are back where you started, and `deleteme` has fulfilled its purpose.

May apologies for the delay in replying to this issue. Been busy.

**Comment by jessekrubin** [comment]
@tdarci thanks for the update! I PR-ed in a script to help people get off the ground when using the repo #2
